server:
  port: 8761

spring:
  application:
    name: flipkart-service-registry
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://flipkart-service-registry.onrender.com



