server:
  port: 6782
spring:
  application:
    name: flipkart-api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product,/
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/otp/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - AuthFilter
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/order/**
          filters:
            - AuthFilter
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/payment/**
          filters:
            - AuthFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowed-headers:
              - '*'
            allowed-methods:
              - GET
              - POST
              - PUT
eureka:
  client:
    service-url:
      defaultZone: https://flipkart-service-registry.onrender.com

